spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/shop_db
    username: shop
    password: shop
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  defer-datasource-initialization: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

file:
  upload-dir: uploads/products

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
